import { Product } from '../../product/entities/product.entity';

// random generate of products Partial
export const MOCK_PRODUCTS: Partial<Product>[] = [
  { name: 'Cheese - Asiago' } as Partial<Product>,
  { name: 'Mikes Hard Lemonade' } as Partial<Product>,
  { name: 'Pail - 15l White-With Handle' } as Partial<Product>,
  { name: 'Tomatoes - Vine Ripe-Red' } as Partial<Product>,
  { name: 'Catfish - Fillets' } as Partial<Product>,
  { name: 'Beer - Sleemans Honey Brown' } as Partial<Product>,
  { name: 'Bread - Assorted Rolls' } as Partial<Product>,
  { name: 'Ostrich - Fan Fillet' } as Partial<Product>,
  { name: 'Rice - Basmati' } as Partial<Product>,
  { name: 'Lettuce - Spring Mix' } as Partial<Product>,
  { name: 'Ham - Cooked Italian' } as Partial<Product>,
  { name: 'Syrup - Kahlua Chocolate' } as Partial<Product>,
  { name: 'Veal - Striploin' } as Partial<Product>,
  { name: 'Muffin Chocolate Individual Wrap' } as Partial<Product>,
  { name: 'Tomato - Tricolor Cherry' } as Partial<Product>,
  { name: 'Tuna - Salad Premix' } as Partial<Product>,
  { name: 'Soup - Base Broth Beef' } as Partial<Product>,
  { name: 'Roe - Lump Fish-Black' } as Partial<Product>,
  { name: 'Daves Island Stinger' } as Partial<Product>,
  { name: 'Flavouring - Raspberry' } as Partial<Product>,
  { name: 'Chocolate - Compound Coating' } as Partial<Product>,
  { name: 'Nantucket Apple Juice' } as Partial<Product>,
  { name: 'Curry Paste - Madras' } as Partial<Product>,
  { name: 'Lid - Translucent-3.5 And 6 Oz' } as Partial<Product>,
  { name: 'Lychee - Canned' } as Partial<Product>,
  { name: 'Wine - Marlbourough Sauv Blanc' } as Partial<Product>,
  { name: 'Sachet' } as Partial<Product>,
  { name: 'Sole - Iqf' } as Partial<Product>,
  { name: 'Ecolab - Hobart Upr Prewash Arm' } as Partial<Product>,
  { name: 'Muffin Batt - Ban Dream Zero' } as Partial<Product>,
  { name: 'Vinegar - Balsamic-White' } as Partial<Product>,
  { name: 'Tart Shells - Savory-3' } as Partial<Product>,
  { name: 'Tomatoes - Cherry' } as Partial<Product>,
  { name: 'Island Oasis - Lemonade' } as Partial<Product>,
  { name: 'Bread Fig And Almond' } as Partial<Product>,
  { name: 'Nut - Pecan-Halves' } as Partial<Product>,
  { name: 'Mcguinness - Blue Curacao' } as Partial<Product>,
  { name: 'Chives - Fresh' } as Partial<Product>,
  { name: 'Jam - Apricot' } as Partial<Product>,
  { name: 'Rice - Jasmine Sented' } as Partial<Product>,
  { name: 'Corn - Mini' } as Partial<Product>,
  { name: 'Country Roll' } as Partial<Product>,
  { name: 'Sprouts - Alfalfa' } as Partial<Product>,
  { name: 'Star Fruit' } as Partial<Product>,
  { name: 'Sorrel - Fresh' } as Partial<Product>,
  { name: 'Latex Rubber Gloves Size 9' } as Partial<Product>,
  { name: 'Beer - Maudite' } as Partial<Product>,
  { name: 'Limes' } as Partial<Product>,
  { name: 'Okra' } as Partial<Product>,
  { name: 'Crab - Meat Combo' } as Partial<Product>,
  { name: 'Tofu - Firm' } as Partial<Product>,
  { name: 'Wine - White-Colubia Cresh' } as Partial<Product>,
  { name: 'Bagelers - Cinn / Brown Sugar' } as Partial<Product>,
  { name: 'Pheasants - Whole' } as Partial<Product>,
  { name: 'Miso Paste White' } as Partial<Product>,
  { name: 'Lemonade - Mandarin-591 Ml' } as Partial<Product>,
  { name: 'Rum - Mount Gay Eclipes' } as Partial<Product>,
  { name: 'Ocean Spray - Kiwi Strawberry' } as Partial<Product>,
  { name: 'Syrup - Golden-Lyles' } as Partial<Product>,
  { name: 'Pumpkin - Seed' } as Partial<Product>,
  { name: 'Lemon Pepper' } as Partial<Product>,
  { name: 'Chocolate - Milk-Callets' } as Partial<Product>,
  { name: 'Island Oasis - Pina Colada' } as Partial<Product>,
  { name: 'Beer - Camerons Cream Ale' } as Partial<Product>,
  { name: 'Carbonated Water - Peach' } as Partial<Product>,
  { name: 'Lamb Shoulder Boneless Nz' } as Partial<Product>,
  { name: 'Lamb - Leg-Boneless' } as Partial<Product>,
  { name: 'Cod - Salted-Boneless' } as Partial<Product>,
  { name: 'Pork - Ham-Virginia' } as Partial<Product>,
  { name: 'Juice - Orangina' } as Partial<Product>,
  { name: 'Marjoram - Dried-Rubbed' } as Partial<Product>,
  { name: 'Lamb - Loin Chops' } as Partial<Product>,
  { name: 'Table Cloth 120 Round White' } as Partial<Product>,
  { name: 'Butter - Pod' } as Partial<Product>,
  { name: 'Oil - Cooking Spray' } as Partial<Product>,
  { name: 'Fruit Mix - Light' } as Partial<Product>,
  { name: 'Dill - Primerba-Paste' } as Partial<Product>,
  { name: 'Spice - Onion Powder Granulated' } as Partial<Product>,
  { name: 'Coffee Swiss Choc Almond' } as Partial<Product>,
  { name: 'Sweet Pea Sprouts' } as Partial<Product>,
  { name: 'Latex Rubber Gloves Size 9' } as Partial<Product>,
  { name: 'Temperature Recording Station' } as Partial<Product>,
  { name: 'Pears - Bosc' } as Partial<Product>,
  { name: 'Hummus - Spread' } as Partial<Product>,
  { name: 'Lamb - Shoulder' } as Partial<Product>,
  { name: 'Shrimp - Black Tiger 13/15' } as Partial<Product>,
  { name: 'Appetizer - Seafood Assortment' } as Partial<Product>,
  { name: 'Grouper - Fresh' } as Partial<Product>,
  { name: 'Tomatoes - Plum-Canned' } as Partial<Product>,
  { name: 'Laundry - Bag Cloth' } as Partial<Product>,
  { name: 'Coffee Caramel Biscotti' } as Partial<Product>,
  { name: 'Artichokes - Knobless-White' } as Partial<Product>,
  { name: 'Cookie Trail Mix' } as Partial<Product>,
  { name: '7up Diet-355 Ml' } as Partial<Product>,
  { name: 'Calypso - Pineapple Passion' } as Partial<Product>,
  { name: 'Oil - Olive-Extra Virgin' } as Partial<Product>,
  { name: 'Chef Hat 25cm' } as Partial<Product>,
  { name: 'Doilies - 12-Paper' } as Partial<Product>,
  { name: 'Oyster - In Shell' } as Partial<Product>,
  { name: 'Beef Cheek Fresh' } as Partial<Product>,
  { name: 'Lemonade - Kiwi-591 Ml' } as Partial<Product>,
  { name: 'Eggplant Oriental' } as Partial<Product>,
  { name: 'Yeast Dry - Fleischman' } as Partial<Product>,
  { name: 'Coconut - Shredded-Sweet' } as Partial<Product>,
  { name: 'Stock - Veal-Brown' } as Partial<Product>,
  { name: 'Tray - Foam-Square 4 - S' } as Partial<Product>,
  { name: 'Wine - Beaujolais Villages' } as Partial<Product>,
  { name: 'Cheese Cloth No 60' } as Partial<Product>,
  { name: 'Ecolab - Balanced Fusion' } as Partial<Product>,
  { name: 'Veal - Striploin' } as Partial<Product>,
  { name: 'Nut - Hazelnut-Whole' } as Partial<Product>,
  { name: 'Lemons' } as Partial<Product>,
  { name: 'Chicken - Wieners' } as Partial<Product>,
  { name: 'Bread - Ciabatta Buns' } as Partial<Product>,
  { name: 'Beer - Camerons Cream Ale' } as Partial<Product>,
  { name: 'Huck Towels White' } as Partial<Product>,
  { name: 'Lime Cordial - Roses' } as Partial<Product>,
  { name: 'Scallop - St. Jaques' } as Partial<Product>,
  { name: 'Venison - Denver Leg Boneless' } as Partial<Product>,
  { name: 'Bagel - Everything Presliced' } as Partial<Product>,
  { name: 'Sauce - Bernaise-Mix' } as Partial<Product>,
  { name: 'Wine - Mas Chicet Rose-Vintage' } as Partial<Product>,
  { name: 'Cocoa Butter' } as Partial<Product>,
  { name: 'Burger Veggie' } as Partial<Product>,
  { name: 'Water-Tap' } as Partial<Product>,
  { name: 'Lettuce - Lolla Rosa' } as Partial<Product>,
  { name: 'Tray - 12in Rnd Blk' } as Partial<Product>,
  { name: 'Table Cloth 144x90 White' } as Partial<Product>,
  { name: 'Crab - Meat' } as Partial<Product>,
  { name: 'Lemons' } as Partial<Product>,
  { name: 'Tart Shells - Sweet-3' } as Partial<Product>,
  { name: 'Cheese - Bakers Cream Cheese' } as Partial<Product>,
  { name: 'Pastry - Raisin Muffin - Mini' } as Partial<Product>,
  { name: 'Nut - Pumpkin Seeds' } as Partial<Product>,
  { name: 'Doilies - 5-Paper' } as Partial<Product>,
  { name: 'Oil - Coconut' } as Partial<Product>,
  { name: 'Beer - Paulaner Hefeweisse' } as Partial<Product>,
  { name: 'Pasta - Fusili Tri - Coloured' } as Partial<Product>,
  { name: 'Bacardi Raspberry' } as Partial<Product>,
  { name: 'Pear - Prickly' } as Partial<Product>,
  { name: 'Wine - Gewurztraminer Pierre' } as Partial<Product>,
  { name: 'Squash - Pattypan-Yellow' } as Partial<Product>,
  { name: 'Soup - Campbells Broccoli' } as Partial<Product>,
  { name: 'Beef - Tenderloin Tails' } as Partial<Product>,
  { name: 'Salmon Atl.whole 8 - 10 Lb' } as Partial<Product>,
  { name: 'Chicken - Breast-5 - 7 Oz' } as Partial<Product>,
  { name: 'Paste - Black Olive' } as Partial<Product>,
  { name: 'Lettuce - Treviso' } as Partial<Product>,
  { name: 'Chicken - Whole Fryers' } as Partial<Product>,
  { name: 'Cookie Double Choco' } as Partial<Product>,
  { name: 'Sprouts Dikon' } as Partial<Product>,
  { name: 'Chocolate - Dark Callets' } as Partial<Product>,
  { name: 'Bread Bowl Plain' } as Partial<Product>,
  { name: 'Arctic Char - Fillets' } as Partial<Product>,
  { name: 'Wine - Sauvignon Blanc Oyster' } as Partial<Product>,
  { name: 'Sauce - Soy Low Sodium - 3.87l' } as Partial<Product>,
  { name: 'Mushroom - White Button' } as Partial<Product>,
  { name: 'Nantucket Pine Orangebanana' } as Partial<Product>,
  { name: 'Sprouts - Brussel' } as Partial<Product>,
  { name: 'Cheese - Cheddarsliced' } as Partial<Product>,
  { name: 'Pork - Back-Short Cut-Boneless' } as Partial<Product>,
  { name: 'Tart - Raisin And Pecan' } as Partial<Product>,
  { name: 'Tilapia - Fillets' } as Partial<Product>,
  { name: 'Pepper - Black-Crushed' } as Partial<Product>,
  { name: 'Puree - Guava' } as Partial<Product>,
  { name: 'Pear - Packum' } as Partial<Product>,
  { name: 'Juice - Grape-White' } as Partial<Product>,
  { name: 'Coffee Decaf Colombian' } as Partial<Product>,
  { name: 'Wine - George Duboeuf Rose' } as Partial<Product>,
  { name: 'Goulash Seasoning' } as Partial<Product>,
  { name: 'Sauce - Soy Low Sodium - 3.87l' } as Partial<Product>,
  { name: 'Dehydrated Kelp Kombo' } as Partial<Product>,
  { name: 'Wine - Zinfandel California 2002' } as Partial<Product>,
  { name: 'Pepper - Red-Finger Hot' } as Partial<Product>,
  { name: 'Cocoa Butter' } as Partial<Product>,
  { name: 'Bread - Roll-Calabrese' } as Partial<Product>,
  { name: 'Orange - Tangerine' } as Partial<Product>,
  { name: 'Tamarind Paste' } as Partial<Product>,
  { name: 'Crab - Claws-Snow 16 - 24' } as Partial<Product>,
  { name: 'Appetizer - Mushroom Tart' } as Partial<Product>,
  { name: 'Grapes - Black' } as Partial<Product>,
  { name: 'Nantucket Cranberry Juice' } as Partial<Product>,
  { name: 'Pail - 15l White-With Handle' } as Partial<Product>,
  { name: 'Cheese - Pont Couvert' } as Partial<Product>,
  { name: 'Crush - Cream Soda' } as Partial<Product>,
  { name: 'Rice Wine - Aji Mirin' } as Partial<Product>,
  { name: 'Compound - Raspberry' } as Partial<Product>,
  { name: 'Latex Rubber Gloves Size 9' } as Partial<Product>,
  { name: 'Squash - Acorn' } as Partial<Product>,
  { name: 'Sausage - Andouille' } as Partial<Product>,
  { name: 'Puree - Blackcurrant' } as Partial<Product>,
  { name: 'Bagel - Plain' } as Partial<Product>,
  { name: 'Olives - Kalamata' } as Partial<Product>,
  { name: 'Lamb - Bones' } as Partial<Product>,
  { name: 'Calypso - Lemonade' } as Partial<Product>,
  { name: 'Papayas' } as Partial<Product>,
  { name: 'Tea - Herbal I Love Lemon' } as Partial<Product>,
  { name: 'Whmis - Spray Bottle Trigger' } as Partial<Product>,
  { name: 'Chicken - White Meat With Tender' } as Partial<Product>,
  { name: 'Liners - Banana-Paper' } as Partial<Product>,
  { name: 'Coffee - Decaffeinato Coffee' } as Partial<Product>,
  { name: 'Wine - Casillero Del Diablo' } as Partial<Product>,
  { name: 'Table Cloth 81x81 Colour' } as Partial<Product>,
  { name: 'English Muffin' } as Partial<Product>,
  { name: 'Lid Coffeecup 12oz D9542b' } as Partial<Product>,
  { name: 'Nut - Pumpkin Seeds' } as Partial<Product>,
  { name: 'Nut - Walnut-Chopped' } as Partial<Product>,
  { name: 'Soup Bowl Clear 8oz92008' } as Partial<Product>,
  { name: 'Bread Fig And Almond' } as Partial<Product>,
  { name: 'Roe - Lump Fish-Red' } as Partial<Product>,
  { name: 'Beer - True North Strong Ale' } as Partial<Product>,
  { name: 'Lettuce - Arugula' } as Partial<Product>,
  { name: 'Beans - Black Bean-Canned' } as Partial<Product>,
  { name: 'Veal Inside - Provimi' } as Partial<Product>,
  { name: 'Longos - Chicken Cordon Bleu' } as Partial<Product>,
  { name: 'Ginger - Ground' } as Partial<Product>,
  { name: 'Mace' } as Partial<Product>,
  { name: 'Steel Wool' } as Partial<Product>,
  { name: 'Grapes - Red' } as Partial<Product>,
  { name: 'Spice - Montreal Steak Spice' } as Partial<Product>,
  { name: 'Roe - White Fish' } as Partial<Product>,
  { name: 'Juice - V8 Splash' } as Partial<Product>,
  { name: 'Irish Cream - Baileys' } as Partial<Product>,
  { name: 'Compound - Pear' } as Partial<Product>,
  { name: 'Bowl 12 Oz - Showcase 92012' } as Partial<Product>,
  { name: 'Nut - Cashews-Whole-Raw' } as Partial<Product>,
  { name: 'Lotus Root' } as Partial<Product>,
  { name: 'Longos - Chicken Cordon Bleu' } as Partial<Product>,
  { name: 'Bagel - 12 Grain Preslice' } as Partial<Product>,
  { name: 'Tomatoes - Cherry' } as Partial<Product>,
  { name: 'Pie Shells 10' } as Partial<Product>,
  { name: 'Wine - Pinot Noir Mondavi Coastal' } as Partial<Product>,
  { name: 'Corn - Mini' } as Partial<Product>,
  { name: 'Veal - Provimi Inside' } as Partial<Product>,
  { name: 'White Fish - Filets' } as Partial<Product>,
  { name: 'Milkettes - 2%' } as Partial<Product>,
  { name: 'Red Snapper - Fillet-Skin On' } as Partial<Product>,
  { name: 'Salsify-Organic' } as Partial<Product>,
  { name: 'Shrimp - Black Tiger 13/15' } as Partial<Product>,
  { name: 'Hold Up Tool Storage Rack' } as Partial<Product>,
  { name: 'Pur Source' } as Partial<Product>,
  { name: 'Aspic - Amber' } as Partial<Product>,
  { name: 'Bread - Bagels-Plain' } as Partial<Product>,
  { name: 'Quail Eggs - Canned' } as Partial<Product>,
  { name: 'Butter - Unsalted' } as Partial<Product>,
  { name: 'Soup - Campbells Beef Strogonoff' } as Partial<Product>,
  { name: 'Wine - Two Oceans Cabernet' } as Partial<Product>,
  { name: 'Icecream Cone - Areo Chocolate' } as Partial<Product>,
  { name: 'Wine - Ruffino Chianti Classico' } as Partial<Product>,
  { name: 'Lettuce Romaine Chopped' } as Partial<Product>,
  { name: 'Cumin - Whole' } as Partial<Product>,
  { name: 'Bar Mix - Pina Colada-355 Ml' } as Partial<Product>,
  { name: 'Wine - Gewurztraminer Pierre' } as Partial<Product>,
  { name: 'Oregano - Fresh' } as Partial<Product>,
  { name: 'Wine - Clavet Saint Emilion' } as Partial<Product>,
  { name: 'Soda Water - Club Soda-355 Ml' } as Partial<Product>,
  { name: 'Coconut - Whole' } as Partial<Product>,
  { name: 'Tea - Vanilla Chai' } as Partial<Product>,
  { name: 'Juice - Orangina' } as Partial<Product>,
  { name: 'Marjoram - Fresh' } as Partial<Product>,
  { name: 'Chicken - Wings-Tip Off' } as Partial<Product>,
  { name: 'Chicken Breast Halal' } as Partial<Product>,
  { name: 'Flower - Commercial Spider' } as Partial<Product>,
  { name: 'Tofu - Firm' } as Partial<Product>,
  { name: 'Smoked Paprika' } as Partial<Product>,
  { name: 'Cup - Paper 10oz 92959' } as Partial<Product>,
  { name: 'Corn Shoots' } as Partial<Product>,
  { name: 'Pepper - Julienne-Frozen' } as Partial<Product>,
  { name: 'Cookies - Fortune' } as Partial<Product>,
  { name: 'Snapple Raspberry Tea' } as Partial<Product>,
  { name: 'Tea - Herbal Sweet Dreams' } as Partial<Product>,
  { name: 'Pie Filling - Cherry' } as Partial<Product>,
  { name: 'Mix Pina Colada' } as Partial<Product>,
  { name: 'Mahi Mahi' } as Partial<Product>,
  { name: 'Jam - Raspberry' } as Partial<Product>,
  { name: 'Beans - Black Bean-Canned' } as Partial<Product>,
  { name: 'Wine - Placido Pinot Grigo' } as Partial<Product>,
  { name: 'Flower - Daisies' } as Partial<Product>,
  { name: 'Beer - Moosehead' } as Partial<Product>,
  { name: 'Flour - Corn-Fine' } as Partial<Product>,
  { name: 'Bok Choy - Baby' } as Partial<Product>,
  { name: 'Chips - Miss Vickies' } as Partial<Product>,
  { name: 'Mushroom - Shitake-Dry' } as Partial<Product>,
  { name: 'Tea - Vanilla Chai' } as Partial<Product>,
  { name: 'Tomato - Green' } as Partial<Product>,
  { name: 'Beer - Tetleys' } as Partial<Product>,
  { name: 'Dr. Pepper - 355ml' } as Partial<Product>,
  { name: 'Cheese - Goat' } as Partial<Product>,
  { name: 'Rosemary - Fresh' } as Partial<Product>,
  { name: 'Pepper - Jalapeno' } as Partial<Product>,
  { name: 'Marsala - Sperone-Fine-D.o.c.' } as Partial<Product>,
  { name: 'Orange - Canned-Mandarin' } as Partial<Product>,
  { name: 'Absolut Citron' } as Partial<Product>,
  { name: 'Absolut Citron' } as Partial<Product>,
  { name: 'Pork - Bones' } as Partial<Product>,
  { name: 'Pasta - Shells-Medium-Dry' } as Partial<Product>,
  { name: 'Cheese - Boursin-Garlic / Herbs' } as Partial<Product>,
  { name: 'Worcestershire Sauce' } as Partial<Product>,
  { name: 'Juice - Apple Cider' } as Partial<Product>,
  { name: 'Wine - Dubouef Macon - Villages' } as Partial<Product>,
  { name: 'Flour - Cake' } as Partial<Product>,
  { name: 'Beef - Rouladin-Sliced' } as Partial<Product>,
  { name: 'Bagel - Plain' } as Partial<Product>,
  { name: 'Red Snapper - Fresh-Whole' } as Partial<Product>,
  { name: 'Rolled Oats' } as Partial<Product>,
  { name: 'Wine - Conde De Valdemar' } as Partial<Product>,
  { name: 'Bread - Hamburger Buns' } as Partial<Product>,
  { name: 'Beef - Kindney-Whole' } as Partial<Product>,
  { name: 'Veal - Tenderloin-Untrimmed' } as Partial<Product>,
  { name: 'Devonshire Cream' } as Partial<Product>,
  { name: 'Yeast Dry - Fleischman' } as Partial<Product>,
  { name: 'Spice - Pepper Portions' } as Partial<Product>,
  { name: 'Puff Pastry - Sheets' } as Partial<Product>,
  { name: 'Lamb - Loin Chops' } as Partial<Product>,
  { name: 'Cabbage - Nappa' } as Partial<Product>,
  { name: 'Chambord Royal' } as Partial<Product>,
  { name: 'Beef - Prime Rib Aaa' } as Partial<Product>,
  { name: 'Wine - Prem Select Charddonany' } as Partial<Product>,
  { name: 'Tea - Grapefruit Green Tea' } as Partial<Product>,
  { name: 'Pork Salted Bellies' } as Partial<Product>,
  { name: 'Sunflower Seed Raw' } as Partial<Product>,
  { name: 'Gatorade - Orange' } as Partial<Product>,
  { name: 'Lentils - Green-Dry' } as Partial<Product>,
  { name: 'Appetiser - Bought' } as Partial<Product>,
  { name: 'Beer - Heinekin' } as Partial<Product>,
  { name: 'Bread - White Mini Epi' } as Partial<Product>,
  { name: 'Brownies - Two Bite-Chocolate' } as Partial<Product>,
  { name: 'Club Soda - Schweppes-355 Ml' } as Partial<Product>,
  { name: 'Pepper - White-Whole' } as Partial<Product>,
  { name: 'Ice Cream Bar - Rolo Cone' } as Partial<Product>,
  { name: 'Bread Roll Foccacia' } as Partial<Product>,
  { name: 'Cheese - Havarti-Roasted Garlic' } as Partial<Product>,
  { name: 'Wine - Jafflin Bourgongone' } as Partial<Product>,
  { name: 'Bowl 12 Oz - Showcase 92012' } as Partial<Product>,
  { name: 'Wine - Rubyport' } as Partial<Product>,
  { name: 'Sloe Gin - Mcguinness' } as Partial<Product>,
  { name: 'Broom Handle' } as Partial<Product>,
  { name: 'Sparkling Wine - Rose-Freixenet' } as Partial<Product>,
  { name: 'Cheese - Brie Roitelet' } as Partial<Product>,
  { name: 'Yogurt - French Vanilla' } as Partial<Product>,
  { name: 'Yoghurt Tubes' } as Partial<Product>,
  { name: 'Cheese - Brie Roitelet' } as Partial<Product>,
  { name: 'Gatorade - Orange' } as Partial<Product>,
  { name: 'Scallops - In Shell' } as Partial<Product>,
  { name: 'Pate - Liver' } as Partial<Product>,
  { name: 'Bouq All Italian - Primerba' } as Partial<Product>,
  { name: 'Fish - Bones' } as Partial<Product>,
  { name: 'Pork - Sausage-Medium' } as Partial<Product>,
  { name: 'Cheese - Brie-Triple Creme' } as Partial<Product>,
  { name: 'Glass - Wine-Plastic-Clear 5 Oz' } as Partial<Product>,
  { name: 'Daves Island Stinger' } as Partial<Product>,
  { name: 'Cheese - Blue' } as Partial<Product>,
  { name: 'Yogurt - Banana-175 Gr' } as Partial<Product>,
  { name: 'Wine - White-Cooking' } as Partial<Product>,
  { name: 'Monkfish Fresh - Skin Off' } as Partial<Product>,
  { name: 'Muffin Batt - Choc Chk' } as Partial<Product>,
  { name: 'Eggplant - Regular' } as Partial<Product>,
  { name: 'Appetizer - Escargot Puff' } as Partial<Product>,
  { name: 'Carbonated Water - Cherry' } as Partial<Product>,
  { name: 'Potatoes - Idaho 80 Count' } as Partial<Product>,
  { name: 'Alize Sunset' } as Partial<Product>,
  { name: 'Milk 2% 500 Ml' } as Partial<Product>,
  { name: 'Jam - Raspberry' } as Partial<Product>,
  { name: 'Curry Paste - Green Masala' } as Partial<Product>,
  { name: 'Scallops 60/80 Iqf' } as Partial<Product>,
  { name: 'Sugar - Brown' } as Partial<Product>,
  { name: 'Eggplant - Baby' } as Partial<Product>,
  { name: 'Chicken - Leg-Boneless' } as Partial<Product>,
  { name: 'Water - Tonic' } as Partial<Product>,
  { name: 'Lobster - Tail-3 - 4 Oz' } as Partial<Product>,
  { name: 'Beer - Rickards Red' } as Partial<Product>,
  { name: 'Wine - Fat Bastard Merlot' } as Partial<Product>,
  { name: 'Honey - Lavender' } as Partial<Product>,
  { name: 'Extract Vanilla Pure' } as Partial<Product>,
  { name: 'Lettuce - Sea / Sea Asparagus' } as Partial<Product>,
  { name: 'Lentils - Green Le Puy' } as Partial<Product>,
  { name: 'Nut - Hazelnut-Ground-Natural' } as Partial<Product>,
  { name: 'Pepper - Gypsy Pepper' } as Partial<Product>,
  { name: 'Trout - Hot Smkd-Dbl Fillet' } as Partial<Product>,
  { name: 'Cheese - Shred Cheddar / Mozza' } as Partial<Product>,
  { name: 'Ice - Clear-300 Lb For Carving' } as Partial<Product>,
  { name: 'Shopper Bag - S - 4' } as Partial<Product>,
  { name: 'Beer - Corona' } as Partial<Product>,
  { name: 'Crush - Grape-355 Ml' } as Partial<Product>,
  { name: 'Catfish - Fillets' } as Partial<Product>,
  { name: 'Veal - Brisket-Provimi' } as Partial<Product>,
  { name: 'Oil - Olive Bertolli' } as Partial<Product>,
  { name: 'Chicken - Wings-Tip Off' } as Partial<Product>,
  { name: 'Cheese - Grie Des Champ' } as Partial<Product>,
  { name: 'Sea Bass - Whole' } as Partial<Product>,
  { name: 'Gelatine Powder' } as Partial<Product>,
  { name: 'Chevril' } as Partial<Product>,
  { name: 'Grand Marnier' } as Partial<Product>,
  { name: 'Cocoa Powder - Dutched' } as Partial<Product>,
  { name: 'Tomatoes - Hot House' } as Partial<Product>,
  { name: 'Pasta - Agnolotti - Butternut' } as Partial<Product>,
  { name: 'Tortillas - Flour-12' } as Partial<Product>,
  { name: 'Pasta - Rotini-Dry' } as Partial<Product>,
  { name: 'The Pop Shoppe - Grape' } as Partial<Product>,
  { name: 'Water - Spring Water 500ml' } as Partial<Product>,
  { name: 'Chicken - Thigh-Bone In' } as Partial<Product>,
  { name: 'Wine - White-Riesling-Semi - Dry' } as Partial<Product>,
  { name: 'Huck White Towels' } as Partial<Product>,
  { name: 'Cheese - Mozzarella' } as Partial<Product>,
  { name: 'Stock - Chicken-White' } as Partial<Product>,
  { name: 'Oil - Olive' } as Partial<Product>,
  { name: 'Beans - Turtle-Black-Dry' } as Partial<Product>,
  { name: 'Lid - 0090 Clear' } as Partial<Product>,
  { name: 'Tofu - Soft' } as Partial<Product>,
  { name: 'Cut Wakame - Hanawakaba' } as Partial<Product>,
  { name: 'Placemat - Scallop-White' } as Partial<Product>,
  { name: 'Bread - Rolls-Rye' } as Partial<Product>,
  { name: 'Plaintain' } as Partial<Product>,
  { name: 'Pie Filling - Cherry' } as Partial<Product>,
  { name: 'Mudslide' } as Partial<Product>,
  { name: 'Crab - Claws-Snow 16 - 24' } as Partial<Product>,
  { name: 'Cinnamon - Ground' } as Partial<Product>,
  { name: 'Wine - Cousino Macul Antiguas' } as Partial<Product>,
  { name: 'Pastry - Banana Muffin - Mini' } as Partial<Product>,
  { name: 'Oyster - In Shell' } as Partial<Product>,
  { name: 'Pastry - Baked Cinnamon Stick' } as Partial<Product>,
  { name: 'Soup - Campbells-Cream Of' } as Partial<Product>,
  { name: 'Skirt - 29 Foot' } as Partial<Product>,
  { name: 'Pepper - Green' } as Partial<Product>,
  { name: 'Butter - Unsalted' } as Partial<Product>,
  { name: 'Grand Marnier' } as Partial<Product>,
  { name: 'Lamb - Shoulder-Boneless' } as Partial<Product>,
  { name: 'Onions - Cooking' } as Partial<Product>,
  { name: 'Flour - Masa De Harina Mexican' } as Partial<Product>,
  { name: 'Bread - Pita-Mini' } as Partial<Product>,
  { name: 'Apple - Royal Gala' } as Partial<Product>,
  { name: 'Yogurt - French Vanilla' } as Partial<Product>,
  { name: 'Cream - 10%' } as Partial<Product>,
  { name: 'Loaf Pan - 2 Lb-Foil' } as Partial<Product>,
  { name: 'Rice Pilaf-Dry' } as Partial<Product>,
  { name: 'Bread - Rolls-Rye' } as Partial<Product>,
  { name: 'Sauce - White-Mix' } as Partial<Product>,
  { name: 'Flour Dark Rye' } as Partial<Product>,
  { name: 'Pepper - Julienne-Frozen' } as Partial<Product>,
  { name: 'Compound - Pear' } as Partial<Product>,
  { name: 'Icecream - Dstk Strw Chseck' } as Partial<Product>,
  { name: 'Table Cloth 62x114 Colour' } as Partial<Product>,
  { name: 'Wine - Saint Emilion Calvet' } as Partial<Product>,
  { name: 'Quail Eggs - Canned' } as Partial<Product>,
  { name: 'Puree - Mocha' } as Partial<Product>,
  { name: 'Rice Wine - Aji Mirin' } as Partial<Product>,
  { name: 'Turnip - Mini' } as Partial<Product>,
  { name: 'Juice - Pineapple-48 Oz' } as Partial<Product>,
  { name: 'Trueblue - Blueberry Cranberry' } as Partial<Product>,
  { name: 'Wine - Beringer Founders Estate' } as Partial<Product>,
  { name: 'Mushroom - Crimini' } as Partial<Product>,
  { name: 'Mushroom - Shitake-Dry' } as Partial<Product>,
  { name: 'Tea - Lemon Scented' } as Partial<Product>,
  { name: 'Venison - Liver' } as Partial<Product>,
  { name: 'Vinegar - White' } as Partial<Product>,
  { name: 'Yams' } as Partial<Product>,
  { name: 'Container - Hngd Cll Blk 7x7x3' } as Partial<Product>,
  { name: 'Sprouts - Corn' } as Partial<Product>,
  { name: 'Soup Campbells Turkey Veg.' } as Partial<Product>,
  { name: 'Lobster - Baby-Boiled' } as Partial<Product>,
  { name: 'Salmon - Atlantic-Skin On' } as Partial<Product>,
  { name: 'Cheese - St. Andre' } as Partial<Product>,
  { name: 'Energy Drink Bawls' } as Partial<Product>,
  { name: 'Tomatoes - Grape' } as Partial<Product>,
  { name: 'Chocolate - Milk' } as Partial<Product>,
  { name: 'Flour Dark Rye' } as Partial<Product>,
  { name: 'Orange - Tangerine' } as Partial<Product>,
  { name: 'Bread - Focaccia Quarter' } as Partial<Product>,
  { name: 'Meldea Green Tea Liquor' } as Partial<Product>,
  { name: 'Pasta - Cappellini-Dry' } as Partial<Product>,
  { name: 'Soupcontfoam16oz 116con' } as Partial<Product>,
  { name: 'Wine - Fume Blanc Fetzer' } as Partial<Product>,
  { name: 'Thyme - Fresh' } as Partial<Product>,
  { name: 'Vol Au Vents' } as Partial<Product>,
  { name: 'Longos - Cheese Tortellini' } as Partial<Product>,
  { name: 'Potato - Sweet' } as Partial<Product>,
  { name: 'Quail - Jumbo Boneless' } as Partial<Product>,
  { name: 'Cinnamon Rolls' } as Partial<Product>,
  { name: 'Wine - Ice Wine' } as Partial<Product>,
  { name: 'Chinese Foods - Pepper Beef' } as Partial<Product>,
  { name: 'Quinoa' } as Partial<Product>,
  { name: 'Sauce - Salsa' } as Partial<Product>,
  { name: 'Liners - Baking Cups' } as Partial<Product>,
  { name: 'Chicken - Breast-5 - 7 Oz' } as Partial<Product>,
  { name: 'Pineapple - Golden' } as Partial<Product>,
  { name: 'Truffle Cups - White Paper' } as Partial<Product>,
  { name: 'Mushroom - White Button' } as Partial<Product>,
  { name: 'Juice - Tomato-10 Oz' } as Partial<Product>,
  { name: 'Beef - Baby-Liver' } as Partial<Product>,
  { name: 'Onions Granulated' } as Partial<Product>,
  { name: 'Pepper - Cayenne' } as Partial<Product>,
  { name: 'Cloves - Ground' } as Partial<Product>,
  { name: 'Pastry - Banana Tea Loaf' } as Partial<Product>,
  { name: 'Goat - Whole Cut' } as Partial<Product>,
  { name: 'Squid - U - 10 Thailand' } as Partial<Product>,
  { name: 'Flour - Strong' } as Partial<Product>,
  { name: 'Icecream - Dstk Cml And Fdg' } as Partial<Product>,
  { name: 'Carbonated Water - Orange' } as Partial<Product>,
  { name: 'Wild Boar - Tenderloin' } as Partial<Product>,
  { name: 'Wine - Charddonnay Errazuriz' } as Partial<Product>,
  { name: 'Wine - Tribal Sauvignon' } as Partial<Product>,
  { name: 'Venison - Denver Leg Boneless' } as Partial<Product>,
  { name: 'Bar Mix - Lemon' } as Partial<Product>,
  { name: 'Flour - Semolina' } as Partial<Product>,
  { name: 'Turkey Leg With Drum And Thigh' } as Partial<Product>,
  { name: 'Sambuca - Opal Nera' } as Partial<Product>,
  { name: 'Capon - Breast-Wing On' } as Partial<Product>,
  { name: 'Lid - 3oz Med Rec' } as Partial<Product>,
  { name: 'Cotton Wet Mop 16 Oz' } as Partial<Product>,
  { name: 'Catfish - Fillets' } as Partial<Product>,
  { name: 'Crab - Meat' } as Partial<Product>,
  { name: 'Cactus Pads' } as Partial<Product>,
  { name: 'Salt - Rock-Course' } as Partial<Product>,
  { name: 'Marjoram - Dried-Rubbed' } as Partial<Product>,
  { name: 'Bread - Italian Corn Meal Poly' } as Partial<Product>,
  { name: 'Snapple Lemon Tea' } as Partial<Product>,
  { name: 'Pears - Bosc' } as Partial<Product>,
  { name: 'Shrimp - Baby-Cold Water' } as Partial<Product>,
  { name: 'Ecolab - Balanced Fusion' } as Partial<Product>,
  { name: 'Nut - Peanut-Roasted' } as Partial<Product>,
  { name: 'Wine - Chateau Bonnet' } as Partial<Product>,
  { name: 'Beer - Camerons Cream Ale' } as Partial<Product>,
  { name: 'Stock - Veal-Brown' } as Partial<Product>,
  { name: 'Soup - Knorr-Classic Can. Chili' } as Partial<Product>,
  { name: 'Filling - Mince Meat' } as Partial<Product>,
  { name: 'Longos - Grilled Veg Sandwiches' } as Partial<Product>,
  { name: 'Milk - 2%' } as Partial<Product>,
  { name: 'Vinegar - White Wine' } as Partial<Product>,
  { name: 'Wine - Semi Dry Riesling Vineland' } as Partial<Product>,
  { name: 'Cheese - Grie Des Champ' } as Partial<Product>,
  { name: 'Veal - Liver' } as Partial<Product>,
  { name: 'Hinge W Undercut' } as Partial<Product>,
  { name: 'Limes' } as Partial<Product>,
  { name: 'Wine - Peller Estates Late' } as Partial<Product>,
  { name: 'Cheese - Cheddar-Old White' } as Partial<Product>,
  { name: 'The Pop Shoppe Pinapple' } as Partial<Product>,
  { name: 'Juice - Clamato-341 Ml' } as Partial<Product>,
  { name: 'Corn Meal' } as Partial<Product>,
  { name: 'Lettuce - Spring Mix' } as Partial<Product>,
  { name: 'Bread - Rolls-Corn' } as Partial<Product>,
  { name: 'Cleaner - Pine Sol' } as Partial<Product>,
  { name: 'Pecan Raisin - Tarts' } as Partial<Product>,
  { name: 'Clam Nectar' } as Partial<Product>,
  { name: 'Bread - Sticks-Thin-Plain' } as Partial<Product>,
  { name: 'Pork - Hock And Feet Attached' } as Partial<Product>,
  { name: 'Cookie - Dough Variety' } as Partial<Product>,
  { name: 'Kumquat' } as Partial<Product>,
  { name: 'Skirt - 29 Foot' } as Partial<Product>,
  { name: 'Plastic Arrow Stir Stick' } as Partial<Product>,
  { name: 'Iced Tea - Lemon-340ml' } as Partial<Product>,
  { name: 'Wine - Zinfandel California 2002' } as Partial<Product>,
  { name: 'Wine - Soave Folonari' } as Partial<Product>,
  { name: 'Beans - Fine' } as Partial<Product>,
  { name: 'Beans - Kidney-Canned' } as Partial<Product>,
  { name: 'Raspberries - Fresh' } as Partial<Product>,
  { name: 'Cleaner - Comet' } as Partial<Product>,
  { name: 'Pepper - Green-Chili' } as Partial<Product>,
  { name: 'Sun - Dried Tomatoes' } as Partial<Product>,
  { name: 'Tamarillo' } as Partial<Product>,
  { name: 'Onions - Red Pearl' } as Partial<Product>,
  { name: 'Pepper Squash' } as Partial<Product>,
  { name: 'Carbonated Water - White Grape' } as Partial<Product>,
  { name: 'Soupfoamcont12oz 112con' } as Partial<Product>,
  { name: 'Chutney Sauce - Mango' } as Partial<Product>,
  { name: 'Water - Mineral-Carbonated' } as Partial<Product>,
  { name: 'Table Cloth 120 Round White' } as Partial<Product>,
  { name: 'Cake - Pancake' } as Partial<Product>,
  { name: 'Juice - Mango' } as Partial<Product>,
  { name: 'Pan Grease' } as Partial<Product>,
  { name: 'Soup - Campbells-Cream Of' } as Partial<Product>,
  { name: 'Truffle Shells - White Chocolate' } as Partial<Product>,
  { name: 'Yeast Dry - Fermipan' } as Partial<Product>,
  { name: 'Knife Plastic - White' } as Partial<Product>,
  { name: 'Rice Wine - Aji Mirin' } as Partial<Product>,
  { name: 'Cup - 3.5oz-Foam' } as Partial<Product>,
  { name: 'Country Roll' } as Partial<Product>,
  { name: 'Bag - Bread-White-Plain' } as Partial<Product>,
  { name: 'Rosemary - Fresh' } as Partial<Product>,
  { name: 'Lid - 16 Oz And 32 Oz' } as Partial<Product>,
  { name: 'Longos - Lasagna Beef' } as Partial<Product>,
  { name: 'Juice - Clam-46 Oz' } as Partial<Product>,
  { name: 'Beef - Eye Of Round' } as Partial<Product>,
  { name: 'Bread - Raisin Walnut Oval' } as Partial<Product>,
  { name: 'Brownies - Two Bite-Chocolate' } as Partial<Product>,
  { name: 'Bread - Assorted Rolls' } as Partial<Product>,
  { name: 'Beef - Kobe Striploin' } as Partial<Product>,
  { name: 'Dehydrated Kelp Kombo' } as Partial<Product>,
  { name: 'Chocolate - Semi Sweet-Calets' } as Partial<Product>,
  { name: 'Wine - Periguita Fonseca' } as Partial<Product>,
  { name: 'Trueblue - Blueberry Cranberry' } as Partial<Product>,
  { name: 'Lemons' } as Partial<Product>,
  { name: 'Puree - Mango' } as Partial<Product>,
  { name: 'Maple Syrup' } as Partial<Product>,
  { name: 'Salad Dressing' } as Partial<Product>,
  { name: 'Lotus Leaves' } as Partial<Product>,
  { name: 'Beef - Ox Tail-Frozen' } as Partial<Product>,
  { name: 'Beef - Tender Tips' } as Partial<Product>,
  { name: 'Bandage - Fexible 1x3' } as Partial<Product>,
  { name: 'Lobster - Baby-Boiled' } as Partial<Product>,
  { name: 'Tea - Grapefruit Green Tea' } as Partial<Product>,
  { name: 'Lemon Balm - Fresh' } as Partial<Product>,
  { name: 'Vinegar - Champagne' } as Partial<Product>,
  { name: 'Towel Dispenser' } as Partial<Product>,
  { name: 'Irish Cream - Baileys' } as Partial<Product>,
  { name: 'Five Alive Citrus' } as Partial<Product>,
  { name: 'Tart Shells - Savory-3' } as Partial<Product>,
  { name: 'Wine - Ruffino Chianti Classico' } as Partial<Product>,
  { name: 'Beer - Moosehead' } as Partial<Product>,
  { name: 'Wine - Masi Valpolocell' } as Partial<Product>,
  { name: 'Beer - Rickards Red' } as Partial<Product>,
  { name: 'Beef - Outside-Round' } as Partial<Product>,
  { name: 'Pork - Backs - Boneless' } as Partial<Product>,
  { name: 'Seedlings - Buckwheat-Organic' } as Partial<Product>,
  { name: 'Wine - Rosso Toscano Igt' } as Partial<Product>,
  { name: 'Salmon Steak - Cohoe 6 Oz' } as Partial<Product>,
  { name: 'Stock - Beef-Brown' } as Partial<Product>,
  { name: 'Wine - Stoneliegh Sauvignon' } as Partial<Product>,
  { name: 'Pork - Ground' } as Partial<Product>,
  { name: 'Calypso - Lemonade' } as Partial<Product>,
  { name: 'Quail - Eggs-Fresh' } as Partial<Product>,
  { name: 'Water - Mineral-Natural' } as Partial<Product>,
  { name: 'Wine - Chardonnay Mondavi' } as Partial<Product>,
  { name: 'Foam Tray S2' } as Partial<Product>,
  { name: 'Towel - Roll White' } as Partial<Product>,
  { name: 'Cookies - Oreo-4 Pack' } as Partial<Product>,
  { name: 'Salmon Atl.whole 8 - 10 Lb' } as Partial<Product>,
  { name: 'Cabbage Roll' } as Partial<Product>,
  { name: 'Garbage Bags - Clear' } as Partial<Product>,
  { name: 'Muffin Mix - Chocolate Chip' } as Partial<Product>,
  { name: 'Squid Ink' } as Partial<Product>,
  { name: 'Halibut - Fletches' } as Partial<Product>,
  { name: 'Pork - Liver' } as Partial<Product>,
  { name: 'Marzipan 50/50' } as Partial<Product>,
  { name: 'Lettuce - Arugula' } as Partial<Product>,
  { name: 'Chevril' } as Partial<Product>,
  { name: 'Chocolate Bar - Reese Pieces' } as Partial<Product>,
  { name: 'Eggplant - Regular' } as Partial<Product>,
  { name: 'Coffee - Cafe Moreno' } as Partial<Product>,
  { name: 'Flounder - Fresh' } as Partial<Product>,
  { name: 'Table Cloth 54x54 Colour' } as Partial<Product>,
  { name: 'Potatoes - Mini White 3 Oz' } as Partial<Product>,
  { name: 'Bread - Mini Hamburger Bun' } as Partial<Product>,
  { name: 'Bread Foccacia Whole' } as Partial<Product>,
  { name: 'French Pastries' } as Partial<Product>,
  { name: 'Corn Shoots' } as Partial<Product>,
  { name: 'Pork Loin Bine - In Frenched' } as Partial<Product>,
  { name: 'Steampan Lid' } as Partial<Product>,
  { name: 'Ham - Procutinni' } as Partial<Product>,
  { name: 'Containter - 3oz Microwave Rect.' } as Partial<Product>,
  { name: 'Oil - Canola' } as Partial<Product>,
  { name: 'Bag Clear 10 Lb' } as Partial<Product>,
  { name: 'Extract - Almond' } as Partial<Product>,
  { name: 'Tea Leaves - Oolong' } as Partial<Product>,
  { name: 'Wild Boar - Tenderloin' } as Partial<Product>,
  { name: 'Pickerel - Fillets' } as Partial<Product>,
  { name: 'Cherries - Fresh' } as Partial<Product>,
  { name: 'Bread - Hot Dog Buns' } as Partial<Product>,
  { name: 'Chicken - Soup Base' } as Partial<Product>,
  { name: 'Bar Mix - Lemon' } as Partial<Product>,
  { name: 'Glass Clear 7 Oz Xl' } as Partial<Product>,
  { name: 'Flour - Masa De Harina Mexican' } as Partial<Product>,
  { name: 'Jolt Cola' } as Partial<Product>,
  { name: 'Soup - Campbells-Chix Gumbo' } as Partial<Product>,
  { name: 'Nut - Walnut-Chopped' } as Partial<Product>,
  { name: 'Avocado' } as Partial<Product>,
  { name: 'Mace Ground' } as Partial<Product>,
  { name: 'Carbonated Water - Cherry' } as Partial<Product>,
  { name: 'Beans - Turtle-Black-Dry' } as Partial<Product>,
  { name: 'Butter - Salted' } as Partial<Product>,
  { name: 'Energy Drink - Redbull 355ml' } as Partial<Product>,
  { name: 'Chevere Logs' } as Partial<Product>,
  { name: 'Tamarind Paste' } as Partial<Product>,
  { name: 'Turkey - Breast-Smoked' } as Partial<Product>,
  { name: 'Muffins - Assorted' } as Partial<Product>,
  { name: 'Flour - Teff' } as Partial<Product>,
  { name: 'Wine - Winzer Krems Gruner' } as Partial<Product>,
  { name: 'Plate Pie Foil' } as Partial<Product>,
  { name: 'Juice - Apple-1.36l' } as Partial<Product>,
  { name: 'Cherries - Frozen' } as Partial<Product>,
  { name: 'Potatoes - Yukon Gold-80 Ct' } as Partial<Product>,
  { name: 'Bread - Sticks-Thin-Plain' } as Partial<Product>,
  { name: 'Syrup - Monin-Irish Cream' } as Partial<Product>,
  { name: 'Five Alive Citrus' } as Partial<Product>,
  { name: 'Beef - Kobe Striploin' } as Partial<Product>,
  { name: 'Flower - Leather Leaf Fern' } as Partial<Product>,
  { name: 'Wine - Ej Gallo Sonoma' } as Partial<Product>,
  { name: 'Chicken - Ground' } as Partial<Product>,
  { name: 'Pork - Ground' } as Partial<Product>,
  { name: 'Soup - Campbells Beef Stew' } as Partial<Product>,
  { name: 'Liners - Baking Cups' } as Partial<Product>,
  { name: 'Wine - Jafflin Bourgongone' } as Partial<Product>,
  { name: 'Cake Circle-Paprus' } as Partial<Product>,
  { name: 'Tea - Apple Green Tea' } as Partial<Product>,
  { name: 'Jello - Assorted' } as Partial<Product>,
  { name: 'Flour Dark Rye' } as Partial<Product>,
  { name: 'Beef - Diced' } as Partial<Product>,
  { name: 'Puff Pastry - Sheets' } as Partial<Product>,
  { name: 'Garlic - Elephant' } as Partial<Product>,
  { name: 'Soup - Campbells-Cream Of' } as Partial<Product>,
  { name: 'Soup - Campbells Chili' } as Partial<Product>,
  { name: 'Butter - Unsalted' } as Partial<Product>,
  { name: 'Lotus Rootlets - Canned' } as Partial<Product>,
  { name: 'Asparagus - Frozen' } as Partial<Product>,
  { name: 'Wine - Segura Viudas Aria Brut' } as Partial<Product>,
  { name: 'Coconut Milk - Unsweetened' } as Partial<Product>,
  { name: 'Pie Filling - Cherry' } as Partial<Product>,
  { name: 'Peas - Frozen' } as Partial<Product>,
  { name: 'Bread - Multigrain Oval' } as Partial<Product>,
  { name: 'Salt And Pepper Mix - White' } as Partial<Product>,
  { name: 'Salt - Table' } as Partial<Product>,
  { name: 'Oil - Pumpkinseed' } as Partial<Product>,
  { name: 'Gatorade - Orange' } as Partial<Product>,
  { name: 'Pork - Bacon-Sliced' } as Partial<Product>,
  { name: 'Breadfruit' } as Partial<Product>,
  { name: 'Browning Caramel Glace' } as Partial<Product>,
  { name: 'Tart Shells - Barquettes-Savory' } as Partial<Product>,
  { name: 'Soup - Verve - Chipotle Chicken' } as Partial<Product>,
  { name: 'Wine - Cahors Ac 2000-Clos' } as Partial<Product>,
  { name: 'Juice - Tomato-48 Oz' } as Partial<Product>,
  { name: 'Wine - Maipo Valle Cabernet' } as Partial<Product>,
  { name: 'Silicone Parch. 16.3x24.3' } as Partial<Product>,
  { name: 'Juice Peach Nectar' } as Partial<Product>,
  { name: 'Crab - Meat Combo' } as Partial<Product>,
  { name: 'Jam - Apricot' } as Partial<Product>,
  { name: 'Wine - Cabernet Sauvignon' } as Partial<Product>,
  { name: 'Wine - Chateau Aqueria Tavel' } as Partial<Product>,
  { name: 'Daves Island Stinger' } as Partial<Product>,
  { name: 'Crab - Imitation Flakes' } as Partial<Product>,
  { name: 'Napkin - Cocktail' } as Partial<Product>,
  { name: 'Vinegar - Raspberry' } as Partial<Product>,
  { name: 'Muffin Batt - Blueberry Passion' } as Partial<Product>,
  { name: 'Mangoes' } as Partial<Product>,
  { name: 'Wine - Malbec Trapiche Reserve' } as Partial<Product>,
  { name: 'Gin - Gilbeys London-Dry' } as Partial<Product>,
  { name: 'Oil - Sesame' } as Partial<Product>,
  { name: 'Spice - Onion Powder Granulated' } as Partial<Product>,
  { name: 'Soup Campbells - Tomato Bisque' } as Partial<Product>,
  { name: 'Pasta - Fusili Tri - Coloured' } as Partial<Product>,
  { name: 'Bread - Olive' } as Partial<Product>,
  { name: 'Graham Cracker Mix' } as Partial<Product>,
  { name: 'Limes' } as Partial<Product>,
  { name: 'Tomatillo' } as Partial<Product>,
  { name: 'Cinnamon Buns Sticky' } as Partial<Product>,
  { name: 'Sherry - Dry' } as Partial<Product>,
  { name: 'Bar Energy Chocchip' } as Partial<Product>,
  { name: 'Cinnamon - Ground' } as Partial<Product>,
  { name: 'Rum - Spiced-Captain Morgan' } as Partial<Product>,
  { name: 'Tomatoes - Vine Ripe-Red' } as Partial<Product>,
  { name: 'Fenngreek Seed' } as Partial<Product>,
  { name: 'Blueberries - Frozen' } as Partial<Product>,
  { name: 'Soap - Hand Soap' } as Partial<Product>,
  { name: 'Dehydrated Kelp Kombo' } as Partial<Product>,
  { name: 'Bread - Pain Au Liat X12' } as Partial<Product>,
  { name: 'Foam Espresso Cup Plain White' } as Partial<Product>,
  { name: 'Yogurt - French Vanilla' } as Partial<Product>,
  { name: 'Macaroons - Homestyle Two Bit' } as Partial<Product>,
  { name: 'Red Currants' } as Partial<Product>,
  { name: 'Dried Apple' } as Partial<Product>,
  { name: 'Muffin - Mix - Bran And Maple 15l' } as Partial<Product>,
  { name: 'Tea - Mint' } as Partial<Product>,
  { name: 'Carrots - Mini Red Organic' } as Partial<Product>,
  { name: 'Wine - Chablis 2003 Champs' } as Partial<Product>,
  { name: 'Corn - Cream-Canned' } as Partial<Product>,
  { name: 'Pears - Anjou' } as Partial<Product>,
  { name: 'Soup - Campbells Broccoli' } as Partial<Product>,
  { name: 'Lid - Translucent-3.5 And 6 Oz' } as Partial<Product>,
  { name: 'Wine - Black Tower Qr' } as Partial<Product>,
  { name: 'Parsley Italian - Fresh' } as Partial<Product>,
  { name: 'Gloves - Goldtouch Disposable' } as Partial<Product>,
  { name: 'Grenadillo' } as Partial<Product>,
  { name: 'Pizza Pizza Dough' } as Partial<Product>,
  { name: 'Lettuce - Green Leaf' } as Partial<Product>,
  { name: 'Wine - Pinot Noir Latour' } as Partial<Product>,
  { name: 'Soup Campbells Mexicali Tortilla' } as Partial<Product>,
  { name: 'Snapple - Iced Tea Peach' } as Partial<Product>,
  { name: 'Oil - Peanut' } as Partial<Product>,
  { name: 'Turnip - White' } as Partial<Product>,
  { name: 'Beer - Camerons Auburn' } as Partial<Product>,
  { name: 'Lettuce Romaine Chopped' } as Partial<Product>,
  { name: 'Five Alive Citrus' } as Partial<Product>,
  { name: 'The Pop Shoppe - Black Cherry' } as Partial<Product>,
  { name: 'Bagelers - Cinn / Brown' } as Partial<Product>,
  { name: 'Icecream - Dstk Super Cone' } as Partial<Product>,
  { name: 'Flour - Rye' } as Partial<Product>,
  { name: 'Tea - Vanilla Chai' } as Partial<Product>,
  { name: 'Hot Chocolate - Individual' } as Partial<Product>,
  { name: 'Cheese - Camembert' } as Partial<Product>,
  { name: 'V8 Splash Strawberry Kiwi' } as Partial<Product>,
  { name: 'Cake Sheet Combo Party Pack' } as Partial<Product>,
  { name: 'Tea - Green' } as Partial<Product>,
  { name: 'Relish' } as Partial<Product>,
  { name: 'Versatainer Nc - 888' } as Partial<Product>,
  { name: 'Grapefruit - Pink' } as Partial<Product>,
  { name: 'Cocoa Butter' } as Partial<Product>,
  { name: 'Versatainer Nc - 9388' } as Partial<Product>,
  { name: 'Veal - Inside-Choice' } as Partial<Product>,
  { name: 'Silicone Paper 16.5x24' } as Partial<Product>,
  { name: 'Pate - Liver' } as Partial<Product>,
  { name: 'Chinese Foods - Cantonese' } as Partial<Product>,
  { name: 'Cheese - La Sauvagine' } as Partial<Product>,
  { name: 'Spring Roll Wrappers' } as Partial<Product>,
  { name: 'Quinoa' } as Partial<Product>,
  { name: 'Puree - Passion Fruit' } as Partial<Product>,
  { name: 'Wine - Peller Estates Late' } as Partial<Product>,
  { name: 'V8 - Tropical Blend' } as Partial<Product>,
  { name: 'Chestnuts - Whole' } as Partial<Product>,
  { name: 'Juice - Propel Sport' } as Partial<Product>,
  { name: 'Chick Peas - Dried' } as Partial<Product>,
  { name: 'Dc - Sakura Fu' } as Partial<Product>,
  { name: 'Hold Up Tool Storage Rack' } as Partial<Product>,
  { name: 'Turkey Leg With Drum And Thigh' } as Partial<Product>,
  { name: 'Beef - Top Butt' } as Partial<Product>,
  { name: 'Pepper - Orange' } as Partial<Product>,
  { name: 'Pork - Backfat' } as Partial<Product>,
  { name: 'Quail - Whole-Bone - In' } as Partial<Product>,
  { name: 'Mackerel Whole Fresh' } as Partial<Product>,
  { name: 'Beef - Bresaola' } as Partial<Product>,
  { name: 'Wine - Red-Marechal Foch' } as Partial<Product>,
  { name: 'Pork - Hock And Feet Attached' } as Partial<Product>,
  { name: 'Beer - Blue Light' } as Partial<Product>,
  { name: 'Pineapple - Canned-Rings' } as Partial<Product>,
  { name: 'Oregano - Fresh' } as Partial<Product>,
  { name: 'Blueberries - Frozen' } as Partial<Product>,
  { name: 'Appetizer - Smoked Salmon / Dill' } as Partial<Product>,
  { name: 'Tea - Honey Green Tea' } as Partial<Product>,
  { name: 'Soup - Boston Clam Chowder' } as Partial<Product>,
  { name: 'Apples - Sliced / Wedge' } as Partial<Product>,
  { name: 'Mushroom - Porcini-Dry' } as Partial<Product>,
  { name: 'Cheese - Cottage Cheese' } as Partial<Product>,
  { name: 'Basil - Thai' } as Partial<Product>,
  { name: 'Beer - Sleemans Cream Ale' } as Partial<Product>,
  { name: 'Tomato - Tricolor Cherry' } as Partial<Product>,
  { name: 'Thyme - Lemon-Fresh' } as Partial<Product>,
  { name: 'Egg - Salad Premix' } as Partial<Product>,
  { name: 'Bread Base - Goodhearth' } as Partial<Product>,
  { name: 'Cookies Almond Hazelnut' } as Partial<Product>,
  { name: 'Muffin - Blueberry Individual' } as Partial<Product>,
  { name: 'Vermouth - White-Cinzano' } as Partial<Product>,
  { name: 'Water - Tonic' } as Partial<Product>,
  { name: 'Cod - Black Whole Fillet' } as Partial<Product>,
  { name: 'Samosa - Veg' } as Partial<Product>,
  { name: 'Beef - Inside Round' } as Partial<Product>,
  { name: 'Veal - Striploin' } as Partial<Product>,
  { name: 'Bread Country Roll' } as Partial<Product>,
  { name: 'Milk 2% 500 Ml' } as Partial<Product>,
  { name: 'Ketchup - Tomato' } as Partial<Product>,
  { name: 'Neckerchief Blck' } as Partial<Product>,
  { name: 'Soup - Knorr-Veg / Beef' } as Partial<Product>,
  { name: 'Wine - Gato Negro Cabernet' } as Partial<Product>,
  { name: 'Wine - Two Oceans Sauvignon' } as Partial<Product>,
  { name: 'Fib N9 - Prague Powder' } as Partial<Product>,
  { name: 'Wine - Beringer Founders Estate' } as Partial<Product>,
  { name: 'Towel Multifold' } as Partial<Product>,
  { name: 'Turkey - Breast-Bone - In' } as Partial<Product>,
  { name: 'Pasta - Fusili Tri - Coloured' } as Partial<Product>,
  { name: 'Flower - Commercial Bronze' } as Partial<Product>,
  { name: 'Bread Base - Toscano' } as Partial<Product>,
  { name: 'Table Cloth 54x72 White' } as Partial<Product>,
  { name: 'Swiss Chard' } as Partial<Product>,
  { name: 'Seedlings - Buckwheat-Organic' } as Partial<Product>,
  { name: 'Tart Shells - Savory-3' } as Partial<Product>,
  { name: 'Coffee Swiss Choc Almond' } as Partial<Product>,
  { name: 'Carrots - Jumbo' } as Partial<Product>,
  { name: 'Wine - Maipo Valle Cabernet' } as Partial<Product>,
  { name: 'Calypso - Pineapple Passion' } as Partial<Product>,
  { name: 'Mushroom - Porcini-Dry' } as Partial<Product>,
  { name: 'Sage - Fresh' } as Partial<Product>,
  { name: 'Langers - Ruby Red Grapfruit' } as Partial<Product>,
  { name: 'Shrimp - Baby-Cold Water' } as Partial<Product>,
  { name: 'Beans - French' } as Partial<Product>,
  { name: 'Beans - Wax' } as Partial<Product>,
  { name: 'Cheese Cloth No 100' } as Partial<Product>,
  { name: 'Lamb Tenderloin Nz Fr' } as Partial<Product>,
  { name: 'Wine - Puligny Montrachet A.' } as Partial<Product>,
  { name: 'Flour - So Mix Cake White' } as Partial<Product>,
  { name: 'Beans - Butter Lrg Lima' } as Partial<Product>,
  { name: 'Wine - Cotes Du Rhone' } as Partial<Product>,
  { name: 'Crackers - Graham' } as Partial<Product>,
  { name: 'Oil - Cooking Spray' } as Partial<Product>,
  { name: 'Beef - Bones-Cut - Up' } as Partial<Product>,
  { name: 'Pastry - Trippleberry Muffin - Mini' } as Partial<Product>,
  { name: 'Schnappes - Peach-Walkers' } as Partial<Product>,
  { name: 'Artichokes - Knobless-White' } as Partial<Product>,
  { name: 'Goldschalger' } as Partial<Product>,
  { name: 'Ham - Cooked Bayonne Tinned' } as Partial<Product>,
  { name: 'Wine - Chateau Aqueria Tavel' } as Partial<Product>,
  { name: 'Beans - Black Bean-Canned' } as Partial<Product>,
  { name: 'Wine - Blue Nun Qualitatswein' } as Partial<Product>,
  { name: 'Ham - Smoked-Bone - In' } as Partial<Product>,
  { name: 'Hog / Sausage Casing - Pork' } as Partial<Product>,
  { name: 'Myers Planters Punch' } as Partial<Product>,
  { name: 'Squid - U - 10 Thailand' } as Partial<Product>,
  { name: 'Tuna - Bluefin' } as Partial<Product>,
  { name: 'Wine - Ej Gallo Sierra Valley' } as Partial<Product>,
  { name: 'Sauce - Thousand Island' } as Partial<Product>,
  { name: 'Veal - Inside' } as Partial<Product>,
  { name: 'Foil Wrap' } as Partial<Product>,
  { name: 'Cheese - Brick With Pepper' } as Partial<Product>,
  { name: 'Beef - Outside-Round' } as Partial<Product>,
  { name: 'Aspic - Light' } as Partial<Product>,
  { name: 'Carroway Seed' } as Partial<Product>,
  { name: 'Thyme - Lemon-Fresh' } as Partial<Product>,
  { name: 'Nut - Cashews-Whole-Raw' } as Partial<Product>,
  { name: 'Doilies - 5-Paper' } as Partial<Product>,
  { name: 'Milk - Chocolate 250 Ml' } as Partial<Product>,
  { name: 'Cheese - Pied De Vents' } as Partial<Product>,
  { name: 'Eggplant Italian' } as Partial<Product>,
  { name: 'Quail - Jumbo' } as Partial<Product>,
  { name: 'Onion Powder' } as Partial<Product>,
  { name: 'Bay Leaf' } as Partial<Product>,
  { name: 'Cut Wakame - Hanawakaba' } as Partial<Product>,
  { name: 'Chips - Miss Vickies' } as Partial<Product>,
  { name: 'Shiratamako - Rice Flour' } as Partial<Product>,
  { name: 'Sprouts - Bean' } as Partial<Product>,
  { name: 'Lettuce - Mini Greens-Whole' } as Partial<Product>,
  { name: 'Yogurt - Raspberry-175 Gr' } as Partial<Product>,
  { name: 'Bols Melon Liqueur' } as Partial<Product>,
  { name: 'Soda Water - Club Soda-355 Ml' } as Partial<Product>,
  { name: 'Broom And Broom Rack White' } as Partial<Product>,
  { name: 'Nut - Pine Nuts-Whole' } as Partial<Product>,
  { name: 'Vinegar - White Wine' } as Partial<Product>,
  { name: 'Liners - Baking Cups' } as Partial<Product>,
  { name: 'Sponge Cake Mix - Chocolate' } as Partial<Product>,
  { name: 'Bread - Roll-Italian' } as Partial<Product>,
  { name: 'Cheese - Augre Des Champs' } as Partial<Product>,
  { name: 'Wine - Charddonnay Errazuriz' } as Partial<Product>,
  { name: 'Chocolate - Chips Compound' } as Partial<Product>,
  { name: 'Crab - Dungeness-Whole' } as Partial<Product>,
  { name: 'Stock - Veal-White' } as Partial<Product>,
  { name: 'Pastry - Carrot Muffin - Mini' } as Partial<Product>,
  { name: 'Salmon Atl.whole 8 - 10 Lb' } as Partial<Product>,
  { name: 'Ecolab Crystal Fusion' } as Partial<Product>,
  { name: 'Danishes - Mini Raspberry' } as Partial<Product>,
  { name: 'Wine - Beaujolais Villages' } as Partial<Product>,
  { name: 'Pepsi - 600ml' } as Partial<Product>,
  { name: 'Wine - White-Gewurtzraminer' } as Partial<Product>,
  { name: 'Limes' } as Partial<Product>,
  { name: 'Appetizer - Smoked Salmon / Dill' } as Partial<Product>,
  { name: 'Bread - Corn Muffaletta' } as Partial<Product>,
  { name: 'Sea Bass - Fillets' } as Partial<Product>,
  { name: 'Water - Aquafina Vitamin' } as Partial<Product>,
  { name: 'Lamb Leg - Bone - In Nz' } as Partial<Product>,
  { name: 'Danishes - Mini Raspberry' } as Partial<Product>,
  { name: 'Beans - Yellow' } as Partial<Product>,
  { name: 'Wine - Redchard Merritt' } as Partial<Product>,
  { name: 'Cinnamon Buns Sticky' } as Partial<Product>,
  { name: 'Oil - Sesame' } as Partial<Product>,
  { name: 'Wine - Blue Nun Qualitatswein' } as Partial<Product>,
  { name: 'Milkettes - 2%' } as Partial<Product>,
  { name: 'Lettuce - California Mix' } as Partial<Product>,
  { name: 'Pan Grease' } as Partial<Product>,
  { name: 'Chicken - Leg / Back Attach' } as Partial<Product>,
  { name: 'Table Cloth 54x72 Colour' } as Partial<Product>,
  { name: 'Lettuce - Spring Mix' } as Partial<Product>,
  { name: 'Chicken - Base-Ultimate' } as Partial<Product>,
  { name: 'Roe - Lump Fish-Red' } as Partial<Product>,
  { name: 'Coffee Decaf Colombian' } as Partial<Product>,
  { name: 'Cake Circle-Foil-Scallop' } as Partial<Product>,
  { name: 'Sauce - Caesar Dressing' } as Partial<Product>,
  { name: 'Pasta - Ravioli' } as Partial<Product>,
  { name: 'Snapple - Iced Tea Peach' } as Partial<Product>,
  { name: 'Hot Chocolate - Individual' } as Partial<Product>,
  { name: 'Beans - Black Bean-Preserved' } as Partial<Product>,
  { name: 'Tray - 16in Rnd Blk' } as Partial<Product>,
  { name: 'Nut - Pumpkin Seeds' } as Partial<Product>,
  { name: 'Mushroom Morel Fresh' } as Partial<Product>,
  { name: 'Kellogs Cereal In A Cup' } as Partial<Product>,
  { name: 'Vegetable - Base' } as Partial<Product>,
  { name: 'Curry Paste - Green Masala' } as Partial<Product>,
  { name: 'Lid - High Heat-Super Clear' } as Partial<Product>,
  { name: 'Venison - Racks Frenched' } as Partial<Product>,
  { name: 'Spice - Montreal Steak Spice' } as Partial<Product>,
  { name: 'Appetizer - Asian Shrimp Roll' } as Partial<Product>,
  { name: 'Lamb - Whole Head Off' } as Partial<Product>,
  { name: 'Vinegar - Cider' } as Partial<Product>,
  { name: 'Cherries - Bing-Canned' } as Partial<Product>,
  { name: 'Chocolate - Pistoles-White' } as Partial<Product>,
  { name: 'Pheasants - Whole' } as Partial<Product>,
  { name: 'Buffalo - Short Rib Fresh' } as Partial<Product>,
  { name: 'Soup - Chicken And Wild Rice' } as Partial<Product>,
  { name: 'Schnappes Peppermint - Walker' } as Partial<Product>,
  { name: 'Crab - Back Fin Meat-Canned' } as Partial<Product>,
  { name: 'Wine - Vidal Icewine Magnotta' } as Partial<Product>,
  { name: 'Cardamon Seed / Pod' } as Partial<Product>,
  { name: 'Rhubarb' } as Partial<Product>,
  { name: 'Veal - Insides Provini' } as Partial<Product>,
  { name: 'Venison - Striploin' } as Partial<Product>,
  { name: 'Nantucket Cranberry Juice' } as Partial<Product>,
  { name: 'Beer - Sleemans Honey Brown' } as Partial<Product>,
  { name: 'Onions - Dried-Chopped' } as Partial<Product>,
  { name: 'Sauce - Hoisin' } as Partial<Product>,
  { name: 'Bread - Pumpernickel' } as Partial<Product>,
  { name: 'Hersey Shakes' } as Partial<Product>,
  { name: 'Wine - Ej Gallo Sierra Valley' } as Partial<Product>,
  { name: 'Pineapple - Regular' } as Partial<Product>,
  { name: 'Mushroom Morel Fresh' } as Partial<Product>,
  { name: 'Flower - Daisies' } as Partial<Product>,
  { name: 'Soup - Clam Chowder-Dry Mix' } as Partial<Product>,
  { name: 'Beans - Kidney White' } as Partial<Product>,
  { name: 'Muffin - Mix - Bran And Maple 15l' } as Partial<Product>,
];
